title: frankenye.com
description: My thoughts on all things related to software engineering.
author:
  name: Frank Peña
  email: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: "https://www.github.com/f-enye"
    - platform: stackoverflow
      user_url: "https://stackoverflow.com/users/23373112/francisco-pe%c3%b1a"
    - platform: rss
      user_url: "/feed.xml"

header_pages:
  - about.md

show_excerpts: true
excerpt_separator: <!--more-->

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CNAME
