title: frankenye.com
description: This contains blog posts pertaining to software engineering written by me (Frank Peña).
author:
  name: Frank Peña

# Build settings
remote_theme: jekyll/minima@10124515953527c8990a2de99ae4ddb2a81ffee3
plugins:
  - jekyll-feed
  - jekyll-remote-theme

minima:
  skin: auto
  social_links:
    - platform: github
      user_url: "https://www.github.com/f-enye"
    - platform: stackoverflow
      user_url: "https://stackoverflow.com/users/23373112/francisco-pe%c3%b1a"
    - platform: rss
      user_url: "/feed.xml"

header_pages:
  - about.md

exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CNAME
