title: frankenye.com
description: This contains blog posts pertaining to software engineering written by me (Frank Peña).
github_username: f-enye

# Build settings
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - CNAME